[target.aarch64-linux-ohos]
  compile-option = "-B \"${DEVECO_CANGJIE_HOME}/compiler/third_party/llvm/bin\" -B \"${DEVECO_CANGJIE_HOME}/musl/usr/lib/aarch64-linux-ohos\" -L \"${DEVECO_CANGJIE_HOME}/musl/usr/lib/aarch64-linux-ohos\" -L \"${DEVECO_CANGJIE_HOME}/build/linux_ohos_aarch64_llvm/openssl\" --sysroot \"${DEVECO_CANGJIE_HOME}/musl\""

[dependencies]
  cj_res_entry = {path = "./cj_res", version = "1.0.0"}

[package]
  cjc-version = "0.48.2"
  compile-option = ""
  description = "CangjieUI Application"
  link-option = ""
  name = "ohos_app_cangjie_entry"
  output-type = "dynamic"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
  scripts = {}

[target.aarch64-linux-ohos.bin-dependencies]
  path-option = ["${AARCH64_LIBS}", "${AARCH64_MACRO_LIBS}"]
  package-option = {}


[profile]
  build = {incremental = true, lto = ""}
  customized-option = {debug = "-g -Woff all", release = "--fast-math -O2 -Woff all"}
  test = {}
